name: Publicar GitHub Pages

on:
  push:
    branches:
      - main           # publica sempre que houver push na branch main
  workflow_dispatch:   # ainda permite rodar manualmente

permissions:
  contents: read       # precisa ler os arquivos do repositório
  pages: write         # precisa escrever no GitHub Pages
  id-token: write      # necessário para autenticação

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Pages
        uses: actions/configure-pages@v3

      - name: Upload artefatos
        uses: actions/upload-pages-artifact@v2
        with:
          path: site   # pasta onde está o conteúdo do site

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v2
