name: Publicar GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4   # atualizado

      - name: Configurar Pages
        uses: actions/configure-pages@v4   # atualizado

      - name: Upload artefatos
        uses: actions/upload-pages-artifact@v3   # atualizado
        with:
          path: site

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4   # atualizado
